### PR TITLE
modified aescipher code

### PR DESCRIPTION
**Pull request by JherezTaylor**
Opening PR for discussion @NicholasDanks

### CODE REVIEW

**Comment by NicholasDanks** [comment]
Got you.

**Comment by JherezTaylor** [comment]
Okay, this should fix it, this is all that's in the encrypt method. I haven't tested decrypt but it should work. Note that you can just return the objects in an array on the last line

```
cipher = OpenSSL::Cipher::AES.new(256, :CBC)
cipher.encrypt
cipher.key = Digest::SHA1.hexdigest(key.to_s)
iv = cipher.random_iv
encrypted = cipher.update(document.to_s) + cipher.final
[iv, encrypted]
```

**Comment by JherezTaylor** [comment]
@NicholasDanks Okay, I just confirmed that it passes the encrypt and decrypt tests. For decrypting, recall that the encrypt method returns a regular array that contains the iv and the encrypted text. Don't worry about the json, it doesn't work anyway because it will complain if you try to convert Base64 to UTF-8.

In the decrypt method, it accepts an array and a key, we can access the content of the array by doing 
`decipher.iv = aes_crypt[0]`, then you assign the key in the same way you did before `decipher.key = Digest::SHA1.hexdigest(key.to_s)`. Then do the other stuff and return the decrypted text, you should be good to go from there, if not let us know.

**Comment by NicholasDanks** [comment]
Run options: --seed 27125

# Running:

........................................

Finished in 0.013645s, 2931.5229 runs/s, 4397.2844 assertions/s.

40 runs, 60 assertions, 0 failures, 0 errors, 0 skips

**Comment by NicholasDanks** [comment]
I believe its working now... @JherezTaylor  please check then merge if you are happy.

**Comment by JherezTaylor** [comment]
Lovely

**Comment by JherezTaylor** [comment]
Okay, it's fine. You merge it this time, 

```
git checkout master
git merge AEScipher
git branch -d AEScipher
```

**Pull request merged**
