### PR TITLE
Updated substitution cipher

### PR DESCRIPTION
**Pull request by NicholasDanks**
Sorry for the mixup.

### CODE REVIEW

**Comment by rjollet** [comment]
can you [rebase](https://git-scm.com/docs/git-rebase) and try with the new test

```
git pull
git rebase master permutation_code
```

**Comment by NicholasDanks** [comment]
$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

```
git pull <remote> <branch>
```

If you wish to set tracking information for this branch you can do so with:

```
git branch --set-upstream-to=origin/<branch> permutation_code
```

$ git rebase master permutation_code 
Already on 'permutation_code'
Current branch permutation_code is up to date.

**Comment by JherezTaylor** [comment]
@NicholasDanks after you do a git pull, do a `git checkout permuation_code` this will link the local branch to the one on Github (setting the upstream). Then switch back to master with `git checkout master` and finally, `git rebase master permutation code`, `git push`

**Comment by JherezTaylor** [comment]
Okay, can close now.

**Pull request closed without merging**
